### ISSUE TITLE
Docker images for arm64

### ISSUE THREAD

**Issue by alborotogarcia** [frappe/frappe_docker#380]
Hi!

I need a hand! I've been trying to build frappe images (frappe-worker, erpnext-worker and nginx images) for arm64, although when it comes to run docker-compose up site-creator ends with the following error:

> erpnext-python_1          | Traceback (most recent call last):
> erpnext-python_1          |   File "/home/frappe/frappe-bench/commands/auto_migrate.py", line 64, in <module>
> erpnext-python_1          |     main()
> erpnext-python_1          |   File "/home/frappe/frappe-bench/commands/auto_migrate.py", line 25, in main
> erpnext-python_1          |     save_version_file(version_file)
> erpnext-python_1          |   File "/home/frappe/frappe-bench/commands/utils.py", line 29, in save_version_file
> erpnext-python_1          |     with open(APP_VERSIONS_JSON_FILE, 'w') as f:
> erpnext-python_1          | PermissionError: [Errno 13] Permission denied: 'app_versions.json'
> erpnext-python_1          | PermissionError: [Errno 13] Permission denied: 'app_versions.json'
> erpnext-schedule_1        | Attempt 1 to connect to redis-cache:6379
> erpnext-schedule_1        | Attempt 1 to connect to redis-socketio:6379
> erpnext-schedule_1        | Connections OK
> erpnext-worker-default_1  | Attempt 3 to connect to mariadb:3306
> erpnext-worker-default_1  | Attempt 1 to connect to redis-queue:6379
> erpnext-worker-default_1  | Attempt 1 to connect to redis-cache:6379
> erpnext-worker-default_1  | Attempt 1 to connect to redis-socketio:6379
> erpnext-worker-default_1  | Connections OK
> site-creator_1            | Attempt 3 to connect to mariadb:3306
> site-creator_1            | Attempt 1 to connect to redis-queue:6379
> site-creator_1            | Attempt 1 to connect to redis-cache:6379
> site-creator_1            | Attempt 1 to connect to redis-socketio:6379
> site-creator_1            | Connections OK
> erpnext-worker-long_1     | 21:07:08 Worker rq:worker:bc253f0a65f8469d89dc0dc29f1fbc9e.328a97cc0a77.13.long: started, version 1.6.1
> erpnext-worker-long_1     | 21:07:08 Subscribing to channel rq:pubsub:bc253f0a65f8469d89dc0dc29f1fbc9e.328a97cc0a77.13.long
> erpnext-worker-long_1     | 21:07:08 *** Listening on long...
> erpnext-worker-long_1     | 21:07:08 Cleaning registries for queue: long
> erpnext-worker-short_1    | 21:07:08 Worker rq:worker:62088d0ca5544734a5d1282a5a0b0c70.2bb5e7762199.13.short: started, version 1.6.1
> erpnext-worker-short_1    | 21:07:08 Subscribing to channel rq:pubsub:62088d0ca5544734a5d1282a5a0b0c70.2bb5e7762199.13.short
> erpnext-worker-short_1    | 21:07:08 *** Listening on short...
> erpnext-worker-short_1    | 21:07:08 Cleaning registries for queue: short
> erpnext-worker-default_1  | 21:07:08 Worker rq:worker:2b5763d3c9ce41fba88bca450491e836.ee5dff608393.13.default: started, version 1.6.1
> erpnext-worker-default_1  | 21:07:08 Subscribing to channel rq:pubsub:2b5763d3c9ce41fba88bca450491e836.ee5dff608393.13.default
> erpnext-worker-default_1  | 21:07:08 *** Listening on default...
> erpnext-worker-default_1  | 21:07:08 Cleaning registries for queue: default
> erpnext-schedule_1        | Starting background scheduler . . .
> erpnext-python_1          | [2020-11-16 21:07:09 +0000] [20] [INFO] Starting gunicorn 19.10.0
> erpnext-python_1          | [2020-11-16 21:07:09 +0000] [20] [INFO] Listening at: http://0.0.0.0:8000 (20)
> erpnext-python_1          | [2020-11-16 21:07:09 +0000] [20] [INFO] Using worker: gthread
> erpnext-python_1          | [2020-11-16 21:07:09 +0000] [23] [INFO] Booting worker with pid: 23
> erpnext-python_1          | [2020-11-16 21:07:09 +0000] [24] [INFO] Booting worker with pid: 24
> erpnext-nginx_1           | Frappe-python available on erpnext-python port 8000
> erpnext-nginx_1           | Waiting for frappe-socketio to be available on frappe-socketio port 9000
> erpnext-nginx_1           | Frappe-socketio available on frappe-socketio port 9000
> mariadb_1                 | 2020-11-16 21:07:10 14 [Warning] Access denied for user 'frappe'@'192.168.64.14' (using password: NO)
> site-creator_1            | Created user _69928f0f6369849a
> site-creator_1            | Created database _69928f0f6369849a
> mariadb_1                 | 2020-11-16 21:07:10 15 [Warning] 'proxies_priv' entry '@% root@a795348862ff' ignored in --skip-name-resolve mode.
> site-creator_1            | Granted privileges to user _69928f0f6369849a and database _69928f0f6369849a
> site-creator_1            | Starting database import...
> site-creator_1            | Imported from database /home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/framework_mariadb.sql
> mariadb_1                 | 2020-11-16 21:07:10 16 [Warning] Aborted connection 16 to db: '_69928f0f6369849a' user: '_69928f0f6369849a' host: '192.168.64.14' (Got an error reading communication packets)
> site-creator_1            | 
> site-creator_1            | Installing frappe...
> Updating DocTypes for frappe        : [========================================] 100%
> redis-cache_1             | 1:M 16 Nov 2020 21:08:06.531 * 10000 changes in 60 seconds. Saving...
> redis-cache_1             | 1:M 16 Nov 2020 21:08:06.532 * Background saving started by pid 18
> redis-cache_1             | 18:C 16 Nov 2020 21:08:06.538 * DB saved on disk
> redis-cache_1             | 18:C 16 Nov 2020 21:08:06.540 * RDB: 4 MB of memory used by copy-on-write
> redis-cache_1             | 1:M 16 Nov 2020 21:08:06.632 * Background saving terminated with success
> mariadb_1                 | 2020-11-16 21:08:09 19 [Warning] Access denied for user '_69928f0f6369849a'@'192.168.64.13' (using password: YES)
> Updating country info               : [========================================] 100%
> site-creator_1            | Traceback (most recent call last):
> site-creator_1            |   File "/home/frappe/frappe-bench/commands/new.py", line 106, in <module>
> site-creator_1            |     main()
> site-creator_1            |   File "/home/frappe/frappe-bench/commands/new.py", line 61, in main
> site-creator_1            |     db_port=db_port,
> site-creator_1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 86, in _new_site
> site-creator_1            |     _install_app(app, verbose=verbose, set_as_patched=not source_sql)
> site-creator_1            |   File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 59, in install_app
> site-creator_1            |     raise Exception("App not in apps.txt")
> site-creator_1            | Exception: App not in apps.txt
> mariadb_1                 | 2020-11-16 21:08:19 18 [Warning] Aborted connection 18 to db: '_69928f0f6369849a' user: '_69928f0f6369849a' host: '192.168.64.14' (Got an error reading communication packets)
> traefik_1                 | time="2020-11-16T21:08:20Z" level=debug msg="Provider event received {Status:die ID:3dee763659a53388de61d91db1a3d24522d7153f5a226e600a4a00394815b8f7 From:xx-worker:edge Type:container Action:die Actor:{ID:3dee763659a53388de61d91db1a3d24522d7153f5a226e600a4a00394815b8f7 Attributes:map[com.docker.compose.config-hash:a7250b669a99acbd764b4336d9368408cb424c47a08287c3900efee473282477 com.docker.compose.container-number:1 com.docker.compose.oneoff:False com.docker.compose.project:frappe_docker com.docker.compose.project.config_files:docker-compose.yml com.docker.compose.project.working_dir:/mnt/ssd/dockerfiles/frappe_docker com.docker.compose.service:site-creator com.docker.compose.version:1.27.4 exitCode:1 image:xx-worker:edge name:frappe_docker_site-creator_1]} Scope:local Time:1605560900 TimeNano:1605560900191132521}" providerName=docker
> 

Basically i've been building the images from arm64v8 docker images, eg. arm64v8/nginx or arm64v8/node.

Apparently the mariadb connection fails over and over..  what can i check?

**Comment by revant** [comment]
how did you manage to get the worker and nginx images built for arm64?
Can you share more details. like Dockerfile(s) other files packed in image, anything you experienced?

I don't have arm device to experiment right now but I'm interested. Let me check if I can arrange any device.

Meanwhile, someone else can share their knowledge and experience regarding arm64.

Also, does traefik have arm image? i don't think the one used right now is arm64.

**Comment by alborotogarcia** [comment]
@revant Sorry for the delay, yes traeffik has arm64v8 images see: https://hub.docker.com/r/arm64v8/traefik/tags

By default, a docker pull command will pull the image according to your baremetal arch if available, most of the images are getting built using buildx, the problem comes from frappe images that only rely on amd64.

<b>Frappe worker Dockerfile</b>
<script src="https://gist.github.com/alborotogarcia/ced061935a890fedb9c465fe9023ca08.js"></script>

<b>Frappe nginx Dockerfile</b>
<script src="https://gist.github.com/alborotogarcia/7aa20cdf855642faeb2d568be29f5ae3.js"></script>

<b> Erpnext worker dockerfile</b>
<script src="https://gist.github.com/alborotogarcia/8e5487ae3ba626906cebc8c06ebaa7d1.js"></script>

I built them with the following command, eg. for the frappe worker

export LETSENCRYPT_EMAIL=email@example.com ERPNEXT_VERSION=edge FRAPPE_VERSION=edge MARIADB_HOST=mariadb  MYSQL_ROOT_PASSWORD=admin SITE_NAME=mysite.localhost SITES="mysite.localhost" DB_ROOT_USER=root ADMIN_PASSWORD=admin INSTALL_APPS=erpnext ENTRYPOINT_LABEL=traefik.http.routers.erpnext-nginx.entrypoints=web CERT_RESOLVER_LABEL=erpnext.local.no-cert-resolver HTTPS_REDIRECT_RULE_LABEL=erpnext.local.no-redirect-rule HTTPS_REDIRECT_ENTRYPOINT_LABEL=erpnext.local.no-entrypoint HTTPS_REDIRECT_MIDDLEWARE_LABEL=erpnext.local.no-middleware HTTPS_USE_REDIRECT_MIDDLEWARE_LABEL=erpnext.local-no-redirect-middleware
docker build . -t xx-worker:edge

And so it is the docker-compose.yaml
<script src="https://gist.github.com/alborotogarcia/5b0172016842a757e44af1ab78cebea2.js"></script>

Thank you for your time!

**Comment by webees** [comment]
The same error is reported on a new server, and mariadb works fine.

# erpnext-python
```
Attempt 9 to connect to mariadb:3306
Attempt 10 to connect to mariadb:3306
Connection to mariadb:3306 timed out
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/commands/auto_migrate.py", line 64, in <module>
    main()
  File "/home/frappe/frappe-bench/commands/auto_migrate.py", line 25, in main
    save_version_file(version_file)
  File "/home/frappe/frappe-bench/commands/utils.py", line 29, in save_version_file
    with open(APP_VERSIONS_JSON_FILE, 'w') as f:
PermissionError: [Errno 13] Permission denied: 'app_versions.json'
[2020-11-18 13:03:34 +0000] [22] [INFO] Starting gunicorn 19.10.0
[2020-11-18 13:03:34 +0000] [22] [INFO] Listening at: http://0.0.0.0:8000 (22)
[2020-11-18 13:03:34 +0000] [22] [INFO] Using worker: gthread
[2020-11-18 13:03:34 +0000] [25] [INFO] Booting worker with pid: 25
[2020-11-18 13:03:34 +0000] [26] [INFO] Booting worker with pid: 26`
```
# mariadb
```
2020-11-18 13:00:03+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.3.27+maria~focal started.,
2020-11-18 13:00:03+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql',
2020-11-18 13:00:03+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.3.27+maria~focal started.,
2020-11-18 13:00:03 0 [Note] mysqld (mysqld 10.3.27-MariaDB-1:10.3.27+maria~focal) starting as process 1 ...,
2020-11-18 13:00:03 0 [Note] InnoDB: Using Linux native AIO,
2020-11-18 13:00:03 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins,
2020-11-18 13:00:03 0 [Note] InnoDB: Uses event mutexes,
2020-11-18 13:00:03 0 [Note] InnoDB: Compressed tables use zlib 1.2.11,
2020-11-18 13:00:03 0 [Note] InnoDB: Number of pools: 1,
2020-11-18 13:00:03 0 [Note] InnoDB: Using SSE2 crc32 instructions,
2020-11-18 13:00:03 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M,
2020-11-18 13:00:03 0 [Note] InnoDB: Completed initialization of buffer pool,
2020-11-18 13:00:03 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().,
2020-11-18 13:00:03 0 [Note] InnoDB: 128 out of 128 rollback segments are active.,
2020-11-18 13:00:03 0 [Note] InnoDB: Creating shared tablespace for temporary tables,
2020-11-18 13:00:03 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...,
2020-11-18 13:00:03 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.,
2020-11-18 13:00:03 0 [Note] InnoDB: Waiting for purge to start,
2020-11-18 13:00:03 0 [Note] InnoDB: 10.3.27 started; log sequence number 1625575; transaction id 20,
2020-11-18 13:00:03 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool,
2020-11-18 13:00:03 0 [Note] Plugin 'FEEDBACK' is disabled.,
2020-11-18 13:00:03 0 [Note] InnoDB: Buffer pool(s) load completed at 201118 13:00:03,
2020-11-18 13:00:03 0 [Note] Server socket created on IP: '::'.,
2020-11-18 13:00:03 0 [Warning] 'proxies_priv' entry '@% root@65a4c7847c74' ignored in --skip-name-resolve mode.,
2020-11-18 13:00:03 0 [Note] Reading of all Master_info entries succeeded,
2020-11-18 13:00:03 0 [Note] Added new Master_info '' to hash table,
2020-11-18 13:00:03 0 [Note] mysqld: ready for connections.,
Version: '10.3.27-MariaDB-1:10.3.27+maria~focal'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution,
```

**Comment by webees** [comment]
It seems to be related to selinux.
I spent a lot of time, but still not resolved.

```
PermissionError: [Errno 13] Permission denied: 'app_versions.json'
PermissionError: [Errno 13] Permission denied: './erp.localhost'
```
https://github.com/frappe/frappe_docker/issues/375

**Comment by araven** [comment]
> how did you manage to get the worker and nginx images built for arm64?
> Can you share more details. like Dockerfile(s) other files packed in image, anything you experienced?
> 
> I don't have arm device to experiment right now but I'm interested. Let me check if I can arrange any device.

You don't need to have a physical arm64 device. You can emulate it : [https://gist.github.com/george-hawkins/16ee37063213f348a17717a7007d2c79](https://gist.github.com/george-hawkins/16ee37063213f348a17717a7007d2c79)
> 
> Meanwhile, someone else can share their knowledge and experience regarding arm64.
> 
> images are not ready for arm,
> 
> * does traefik has arm image? i don't think the one used right now is arm64.
> * all images are built from bitnami minideb, not for arm64

The frappe/frappe-nginx, frappe/frappe-worker, frappe/erpnext-nginx and frappe/erpnext-worker images have to be pushed to hub.docker.com using the multiarch [docker buildx feature](https://medium.com/@artur.klauser/building-multi-architecture-docker-images-with-buildx-27d80f7e2408)

**Comment by revant** [comment]
can anyone test `frappe/erpnext-worker:edge`, `frappe/erpnext-nginx:edge` and `frappe/frappe-socketio:edge` images for arm64?

- https://hub.docker.com/r/frappe/frappe-socketio/tags?page=1&ordering=last_updated&name=edge
- https://hub.docker.com/r/frappe/erpnext-worker/tags?page=1&ordering=last_updated&name=edge
- https://hub.docker.com/r/frappe/erpnext-nginx/tags?page=1&ordering=last_updated&name=edge

**Comment by alborotogarcia** [comment]
> can anyone test `frappe/erpnext-worker:edge`, `frappe/erpnext-nginx:edge` and `frappe/frappe-socketio:edge` images for arm64?
> 
> * https://hub.docker.com/r/frappe/frappe-socketio/tags?page=1&ordering=last_updated&name=edge
> * https://hub.docker.com/r/frappe/erpnext-worker/tags?page=1&ordering=last_updated&name=edge
> * https://hub.docker.com/r/frappe/erpnext-nginx/tags?page=1&ordering=last_updated&name=edge

Hi @revant, I appreciate your effort, unfortunately I can't get your containers working, this is the log I get

```
Recreating frappe_docker_erpnext-worker-short_1   ... done
Recreating frappe_docker_erpnext-worker-long_1    ... done
Recreating frappe_docker_erpnext-worker-default_1 ... done
Recreating frappe_docker_erpnext-schedule_1       ... done
Recreating frappe_docker_frappe-socketio_1        ... done
Recreating frappe_docker_site-creator_1           ... done
Attaching to frappe_docker_mariadb_1, frappe_docker_redis-cache_1, frappe_docker_redis-queue_1, frappe_docker_traefik_1, frappe_docker_redis-socketio_1, frappe_docker_erpnext-python_1, frappe_docker_erpnext-nginx_1, frappe_docker_erpnext-worker-long_1, frappe_docker_erpnext-schedule_1, frappe_docker_erpnext-worker-short_1, frappe_docker_erpnext-worker-default_1, frappe_docker_site-creator_1, frappe_docker_frappe-socketio_1
erpnext-python_1          | standard_init_linux.go:211: exec user process caused "exec format error"
erpnext-nginx_1           | standard_init_linux.go:211: exec user process caused "exec format error"
erpnext-schedule_1        | standard_init_linux.go:211: exec user process caused "exec format error"
erpnext-worker-default_1  | standard_init_linux.go:211: exec user process caused "exec format error"
erpnext-worker-long_1     | standard_init_linux.go:211: exec user process caused "exec format error"
erpnext-worker-short_1    | standard_init_linux.go:211: exec user process caused "exec format error"
mariadb_1                 | 2021-01-06 14:53:04+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.3.27+maria~focal started.
mariadb_1                 | 2021-01-06 14:53:04+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mariadb_1                 | 2021-01-06 14:53:04+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.3.27+maria~focal started.
mariadb_1                 | 2021-01-06 14:53:05 0 [Note] mysqld (mysqld 10.3.27-MariaDB-1:10.3.27+maria~focal) starting as process 1 ...
mariadb_1                 | 2021-01-06 14:53:05 0 [Note] InnoDB: Using Linux native AIO
mariadb_1                 | 2021-01-06 14:53:05 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins

```

In case someone's still interested in getting frappe working on arm64 I uploaded my container builds, though I couldn't get them working on arm64 Kubernetes cluster yet..

- alborotogarcia/frappe-arm64:frappe-socketio
- alborotogarcia/frappe-arm64:frappe-nginx
- alborotogarcia/frappe-arm64:frappe-worker

And the docker-compose.yml file

https://gist.github.com/alborotogarcia/bfe9eb76d823494fc0d5d0fa22f22561#file-docker-compose-yml

Regards,

Alboroto Garcia

**Comment by revant** [comment]
I pushed the images directly to frappe/erpnext-* that got overwritten by daily cronjob, I can't find arm builds now.
I'll add them to another registry and share here

**Comment by alborotogarcia** [comment]
@revant that's what I thought, wrong arch build..

btw have you try to run those arm64 builds on top of [helm chart](https://github.com/frappe/helm)?

I've been testing this with pvc as longhorn storage with no luck.. :(

**Comment by revant** [comment]
Check these images

- https://hub.docker.com/r/castlecraft/frappe-socketio/tags?page=1&ordering=last_updated&name=edge
- https://hub.docker.com/r/castlecraft/erpnext-worker/tags?page=1&ordering=last_updated&name=edge
- https://hub.docker.com/r/castlecraft/erpnext-nginx/tags?page=1&ordering=last_updated&name=edge

**Comment by revant** [comment]
Not merged yet. reverted

**Comment by alborotogarcia** [comment]
Hey @revant, 

I've just run it, it keeps waiting for config file to be created..

`erpnext-worker-long_1     | config file not created, retry 19
erpnext-worker-short_1    | config file not created, retry 20
erpnext-schedule_1        | config file not created, retry 21
frappe-socketio_1         | config file not created, retry 19
erpnext-worker-long_1     | config file not created, retry 20
erpnext-worker-short_1    | config file not created, retry 21
erpnext-schedule_1        | config file not created, retry 22
frappe-socketio_1         | config file not created, retry 20
erpnext-nginx_1           | Waiting for frappe-python to be available on erpnext-python port 8000
erpnext-worker-long_1     | config file not created, retry 21
erpnext-worker-short_1    | config file not created, retry 22
erpnext-schedule_1        | config file not created, retry 23
frappe-socketio_1         | config file not created, retry 21
erpnext-worker-long_1     | config file not created, retry 22
erpnext-worker-short_1    | config file not created, retry 23
erpnext-schedule_1        | config file not created, retry 24
frappe-socketio_1         | config file not created, retry 22
erpnext-worker-long_1     | config file not created, retry 23
erpnext-worker-short_1    | config file not created, retry 24
erpnext-schedule_1        | config file not created, retry 25
`

**Comment by revant** [comment]
the python container by default creates the config if there is no config in volume.

Confirm mount points and access for host user and docker user.

When the config file gets created, all containers read from that file.

**Comment by alborotogarcia** [comment]
Hi @revant

I am afraid to say that it still throws errors..

> Creating network "frappe_docker_default" with the default driver
Creating volume "frappe_docker_mariadb-vol" with default driver
Creating volume "frappe_docker_redis-cache-vol" with default driver
Creating volume "frappe_docker_redis-queue-vol" with default driver
Creating volume "frappe_docker_redis-socketio-vol" with default driver
Creating volume "frappe_docker_assets-vol" with default driver
Creating volume "frappe_docker_sites-vol" with default driver
Creating volume "frappe_docker_cert-vol" with default driver
Creating frappe_docker_redis-queue_1     ... done
Creating frappe_docker_mariadb_1         ... done
Creating frappe_docker_traefik_1                ... done
Creating frappe_docker_erpnext-nginx_1          ... done
Creating frappe_docker_redis-socketio_1 ... done
Creating frappe_docker_redis-cache_1     ... done
Creating frappe_docker_erpnext-python_1  ... done
Creating frappe_docker_frappe-socketio_1        ... done
Creating frappe_docker_site-creator_1           ... done
Creating frappe_docker_erpnext-schedule_1       ... done
Creating frappe_docker_erpnext-worker-short_1   ... done
Creating frappe_docker_erpnext-worker-long_1    ... done
Creating frappe_docker_erpnext-worker-default_1 ... done
Attaching to frappe_docker_redis-socketio_1, frappe_docker_mariadb_1, frappe_docker_erpnext-python_1, frappe_docker_redis-cache_1, frappe_docker_redis-queue_1, frappe_docker_traefik_1, frappe_docker_erpnext-nginx_1, frappe_docker_frappe-socketio_1, frappe_docker_erpnext-schedule_1, frappe_docker_erpnext-worker-short_1, frappe_docker_erpnext-worker-default_1, frappe_docker_erpnext-worker-long_1, frappe_docker_site-creator_1
erpnext-python_1          | standard_init_linux.go:211: exec user process caused "exec format error"
erpnext-schedule_1        | standard_init_linux.go:211: exec user process caused "exec format error"
erpnext-worker-default_1  | standard_init_linux.go:211: exec user process caused "exec format error"
erpnext-worker-short_1    | standard_init_linux.go:211: exec user process caused "exec format error"
erpnext-worker-long_1     | standard_init_linux.go:211: exec user process caused "exec format error"
frappe-socketio_1         | config file not created, retry 1
frappe-socketio_1         | config file not created, retry 2
mariadb_1                 | 2021-01-17 12:17:38+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.3.27+maria~focal started.
mariadb_1                 | 2021-01-17 12:17:39+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mariadb_1                 | 2021-01-17 12:17:39+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.3.27+maria~focal started.
mariadb_1                 | 2021-01-17 12:17:39+00:00 [Note] [Entrypoint]: Initializing database files
mariadb_1                 | 
mariadb_1                 | 
mariadb_1                 | PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !


I've checked the pulled images even with the sha256 to be sure that the right OCI runtime is pulled..
Status: Downloaded newer image for castlecraft/erpnext-worker@sha256:4e055b9052c6b0bcff3569b7f2f47290547e4e2a72d3388166b1eeaa7d74e397

Inspecting the images..

>docker inspect bcf59a7224d7 
[
    {
        "Id": "sha256:bcf59a7224d7d72327d60f000e860ac2f8a37335ff927a1d21d665032fdcd05d",
        "RepoTags": [],
        "RepoDigests": [
            "castlecraft/erpnext-worker@sha256:4e055b9052c6b0bcff3569b7f2f47290547e4e2a72d3388166b1eeaa7d74e397"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2021-01-08T00:45:58.193907137Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "root",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/home/frappe/.nvm/versions/node/v12.20.0/bin/:/opt/bitnami/python/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "OS_ARCH=amd64",
                "OS_FLAVOUR=debian-10",
                "OS_NAME=linux",
                "BITNAMI_APP_NAME=python",
                "BITNAMI_IMAGE_VERSION=3.7.9-prod-debian-10-r140",
                "PYTHONUNBUFFERED=1",
                "NVM_DIR=/home/frappe/.nvm",
                "NODE_VERSION=12.20.0"
            ],
            "Cmd": [
                "start"
            ],
            "ArgsEscaped": true,
            "Image": "",
            "Volumes": {
                "/home/frappe/backups": {},
                "/home/frappe/frappe-bench/sites": {}
            },
            "WorkingDir": "/home/frappe/frappe-bench/sites",
            "Entrypoint": [
                "docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "maintainer": "Bitnami <containers@bitnami.com>"
            }
        },
        "Architecture": "arm64",
        "Os": "linux",
        "Size": 1224383332,
        "VirtualSize": 1224383332,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/mnt/ssd/docker/overlay2/fc5399bbaf9d6f48ea795a6a5e49606a4240ba6af32f6b56b9b98c7e3ab3a2ff/diff:/mnt/ssd/docker/overlay2/5c32a2f4058fb45a21ec0001b8483ce801563dab013c65a0b95f674050a5c87d/diff:/mnt/ssd/docker/overlay2/9e1a14d2fd2ca9f7e6e6a4b295f75e9659f605b17e24cf34323a36eb72332daf/diff:/mnt/ssd/docker/overlay2/78bee8eb023b702bce2a079c84474cbdff71164de35a6a01f3dd8204774dfe35/diff:/mnt/ssd/docker/overlay2/37c6306c0e5eb04b11aa7eaa1d0f7ab1b133e04328ae49c2563cc2c84a13e4f9/diff:/mnt/ssd/docker/overlay2/58cf3a36e794d2c5b21a6c34a5005a45a037f4223ec7195c3b258db1a6a78cc3/diff:/mnt/ssd/docker/overlay2/c10e9b7b93d7b7ed09e3f0f15190a6a1e3d1869d508bbd95b97e743c37cbb3c9/diff:/mnt/ssd/docker/overlay2/1eb76be222cc5975e35ae024ff7112192ae917c9c85d805a6178ce0750e3c107/diff:/mnt/ssd/docker/overlay2/32aa097b4b35a9600b4bf646e0ccf1dd90eaa14381e26c76aaa370a03accf5e7/diff:/mnt/ssd/docker/overlay2/0a7825e76c7b95ce6ade1935127468062946f52bad4431d3e303586c202a994f/diff:/mnt/ssd/docker/overlay2/f156deb2b656b22939597c0ef4c08c4701091b1a11c764945a3f3dc44980dd53/diff:/mnt/ssd/docker/overlay2/749756f2e1b6f1c62ec12ce277e004f38f46c8a5d908bfec51a72d7645f88f6f/diff:/mnt/ssd/docker/overlay2/e2ecdeb4cea57a6f13414694cab1576782aaba275ac409086667bc4dbbabbc69/diff:/mnt/ssd/docker/overlay2/2e0fbd7bd2efbb3eac1410f13f7b94e5b948abbd73d5472ec57d288b0d1ca893/diff:/mnt/ssd/docker/overlay2/d1641df037a8339e7c575fb7537e54c25b0b9a4153e6f574271006b0e1ce5407/diff:/mnt/ssd/docker/overlay2/7d6b517aac924c1367193e501bf0862c88bb35f23a5929e356e979b38853c076/diff:/mnt/ssd/docker/overlay2/e5689ec01e1e6010f599ff131e4770e9beec87c4c177197e90e24f0e7599d3fd/diff:/mnt/ssd/docker/overlay2/16d750fffcc2b817eb14e0f6739846f7f1f2eb742233875a773237e871358552/diff:/mnt/ssd/docker/overlay2/de6dfafce8e3bb9e9d7543302c42770ff7d3cd43af4a379109458351b497a5ba/diff:/mnt/ssd/docker/overlay2/90bef83cabbafd737ea7322088436e8b6882b128956bb0449a0e5b3d6acf9173/diff:/mnt/ssd/docker/overlay2/9493be89446c6df581a5e22a5db8511804d2727949a93309f3b1e557bbffb266/diff:/mnt/ssd/docker/overlay2/cfdcd19d7474828ce28e710b2b87c5a67f30868ed3ade6aa2497371fb3848587/diff",
                "MergedDir": "/mnt/ssd/docker/overlay2/4f20dd1dc4f1dbf19d675a0b4538e2655e24f29767797ab6e9b2c6670f8832f7/merged",
                "UpperDir": "/mnt/ssd/docker/overlay2/4f20dd1dc4f1dbf19d675a0b4538e2655e24f29767797ab6e9b2c6670f8832f7/diff",
                "WorkDir": "/mnt/ssd/docker/overlay2/4f20dd1dc4f1dbf19d675a0b4538e2655e24f29767797ab6e9b2c6670f8832f7/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:50429095404d79fef9ca745dc0067576015d06bb1218d4eb4ff7d2eb98402e39",
                "sha256:7c5021a0f7f07fa492cd96fa05062e3dd8f3d86a2c87f3688c176ccb23df2b6f",
                "sha256:aa801c05d5525c6b598603bfadd5bcc0a669a02846af2abce04dc032a7dc4789",
                "sha256:dce6c312b12bcbe8cca87a13a92aca3a79166232fd8a77dc8996dd6a04c43596",
                "sha256:98623796346a4d1ef5b42e1981ba8798938fa1ebaa43ad678f7c757d4e140ab4",
                "sha256:909b2c9964d6b838f4d09524f686b1a7190581623465fb69f3a5128dc6ecc578",
                "sha256:80ef2fdcd0fe4611ddbe843ea71bc2bd395c62630402f7ab90f1dc985004800d",
                "sha256:0bdef36db60bb4ed6281e6f122132d144fcc7b74538770307fec4c7169b1de55",
                "sha256:88d4937d6f0824d54293ebcc8441256019e97af4be85d80c573cc3ccc2996934",
                "sha256:38ecc43a21c48ea61ab53b91787153559ee67855b0353431a0c871ace0e50c84",
                "sha256:57ee07dd03f275bdd3cc61295fdbc905aca2c54b4e0161ac3929f6e1380c2aac",
                "sha256:3e92f13a9dee30224750a6f5fd8a1d75035f6a71ed101965c8ece68029ebf5d5",
                "sha256:e05be256d8ee9d34304f6cc2854d4f484c8d12d9d2dbc22dc382d815f2fad393",
                "sha256:e69492ee3b49b6ad60b8cfeb46dd8aba75be4b6fd623b69d34907c79bf4a6f59",
                "sha256:e0fb91da8f8af007d540590fd9dcac07f8d1d37dc07f7aca20a5846901727ebf",
                "sha256:75fc61e33613fce0108b60e4e595957bbbe3a81516a8d97839d46fe7f8c4df41",
                "sha256:a951101ff6852b0d535747c1640eeb20c006f2cc7b70eef321e08b091c811b50",
                "sha256:8472a82260b4f120b25302f3582850c12d6c1417043ff72ce3e1f515b547b24e",
                "sha256:ca9aad1f7d738638ae93a77700197586862a82906db51ff1cefd263310e9a200",
                "sha256:502ed478bc2e55fa6b49f7fb8790c3883c3593f1ffe7adb050327ce7eb685669",
                "sha256:eda6d3b9e940b1b8c87872d203325d44a19ba8b041d84d32fc4289c7a3a5ec4c",
                "sha256:90868db99756301f2656fe15caeff2216eccfa18498411ff6d331cd74cedf28d",
                "sha256:c5080c3e500ece491970c5b079855ab2ca3d1ac1f87dada90f840876d77887e1"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]

I'd dare to say that their base images looking at the Dockerfiles are built from amd64 ones (ie. python:3.7-slim-buster)

**Comment by revant** [comment]
Okay. I'll check. I'll remove all images from registry and start fresh.

BTW we have the dockerfiles that are compatible with arm64 now. you can build your own images if needed.

**Comment by revant** [comment]
Whoever wants to build the images refer this travis file

```yml
sudo: required

dist: bionic

language: python

python:
  - '3.6'

services:
  - docker

before_install:
  # Install latest docker (https://www.docker.com/blog/multi-arch-build-what-about-travis)
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - docker buildx create --use
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx inspect --bootstrap

  - if [[ "$BUILD" != "development" ]]; then
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
    sudo apt-get update && sudo apt-get -y install git;
    fi
  - if [[ $BUILD == "development" ]];then
    sudo apt-get update && sudo apt-get -y install curl;
    sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose;
    sudo chmod +x /usr/local/bin/docker-compose;
    fi

after_success:
  - docker --version

jobs:
  include:
    - stage: "Build Frappe (all versions)"
      if: branch = develop AND type != pull_request
      script:
        - |
          docker buildx build \
            --no-cache \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-worker:edge \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-worker:develop \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-worker:latest \
            -f build/frappe-worker/Dockerfile .
    - stage: "Build Frappe (all versions)"
      if: branch = develop AND type != pull_request
      script:
        - |
          travis_wait 120 sleep infinity & docker buildx build \
            --no-cache \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-nginx:edge \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-nginx:develop \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-nginx:latest \
            -f build/frappe-nginx/Dockerfile .
    - stage: "Build Frappe (all versions)"
      if: branch = develop AND type != pull_request
      script:
        - |
          docker buildx build \
            --no-cache \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-socketio:edge \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-socketio:develop \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-socketio:latest \
            -f build/frappe-socketio/Dockerfile .
    - stage: "Build ERPNext (all versions)"
      if: branch = develop AND type != pull_request
      script:
        - |
          docker buildx build \
            --no-cache \
            --platform linux/amd64,linux/arm64 \
            --build-arg DOCKER_REGISTRY_PREFIX=${DOCKER_REGISTRY_PREFIX:=frappe} \
            --push \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/erpnext-worker:edge \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/erpnext-worker:develop \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/erpnext-worker:latest \
            -f build/erpnext-worker/Dockerfile .
    - stage: "Build ERPNext (all versions)"
      if: branch = develop AND type != pull_request
      script:
        - |
          travis_wait 120 sleep infinity & docker buildx build \
            --no-cache \
            --platform linux/amd64,linux/arm64 \
            --build-arg DOCKER_REGISTRY_PREFIX=${DOCKER_REGISTRY_PREFIX:=frappe} \
            --push \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/erpnext-nginx:edge \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/erpnext-nginx:develop \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/erpnext-nginx:latest \
            -f build/erpnext-nginx/Dockerfile .
    - stage: "Build Frappe (all versions)"
      if: branch = master AND type != pull_request
      script:
        - |
          git clone https://github.com/frappe/frappe --branch version-13-beta && \
            cd frappe && \
            git fetch --tags && \
            export VERSION=$(git tag --list --sort=-version:refname "v13*" | sed -n 1p | sed -e 's#.*@\(\)#\1#') && \
            cd ..
        - |
          docker buildx build \
            --no-cache \
            --platform linux/amd64,linux/arm64 \
            --build-arg GIT_BRANCH=version-13-beta \
            --push \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-worker:v13 \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-worker:${VERSION} \
            -f build/frappe-worker/Dockerfile .
    - stage: "Build Frappe (all versions)"
      if: branch = master AND type != pull_request
      script:
        - |
          git clone https://github.com/frappe/frappe --branch version-13-beta && \
            cd frappe && \
            git fetch --tags && \
            export VERSION=$(git tag --list --sort=-version:refname "v13*" | sed -n 1p | sed -e 's#.*@\(\)#\1#') && \
            cd ..
        - |
          travis_wait 120 sleep infinity & docker buildx build \
            --no-cache \
            --build-arg GIT_BRANCH=version-13-beta \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-nginx:v13 \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-nginx:${VERSION} \
            -f build/frappe-nginx/Dockerfile .
    - stage: "Build Frappe (all versions)"
      if: branch = master AND type != pull_request
      script:
        - |
          git clone https://github.com/frappe/frappe --branch version-13-beta && \
            cd frappe && \
            git fetch --tags && \
            export VERSION=$(git tag --list --sort=-version:refname "v13*" | sed -n 1p | sed -e 's#.*@\(\)#\1#') && \
            cd ..
        - |
          docker buildx build \
            --no-cache \
            --platform linux/amd64,linux/arm64 \
            --build-arg GIT_BRANCH=version-13-beta \
            --push \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-socketio:v13 \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-socketio:${VERSION} \
            -f build/frappe-socketio/Dockerfile .
    - stage: "Build ERPNext (all versions)"
      if: branch = master AND type != pull_request
      script:
        - |
          git clone https://github.com/frappe/erpnext --branch version-13-beta && \
            cd erpnext && \
            git fetch --tags && \
            export VERSION=$(git tag --list --sort=-version:refname "v13*" | sed -n 1p | sed -e 's#.*@\(\)#\1#') && \
            cd ..
        - |
          docker buildx build \
            --no-cache \
            --platform linux/amd64,linux/arm64 \
            --build-arg GIT_BRANCH=version-13-beta \
            --build-arg DOCKER_REGISTRY_PREFIX=${DOCKER_REGISTRY_PREFIX:=frappe} \
            --push \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/erpnext-worker:v13 \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/erpnext-worker:${VERSION} \
            -f build/erpnext-worker/Dockerfile .
    - stage: "Build ERPNext (all versions)"
      if: branch = master AND type != pull_request
      script:
        - |
          git clone https://github.com/frappe/erpnext --branch version-13-beta && \
            cd erpnext && \
            git fetch --tags && \
            export VERSION=$(git tag --list --sort=-version:refname "v13*" | sed -n 1p | sed -e 's#.*@\(\)#\1#') && \
            cd ..
        - |
          travis_wait 120 sleep infinity & docker buildx build \
            --no-cache \
            --platform linux/amd64,linux/arm64 \
            --build-arg GIT_BRANCH=version-13-beta \
            --build-arg DOCKER_REGISTRY_PREFIX=${DOCKER_REGISTRY_PREFIX:=frappe} \
            --push \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/erpnext-nginx:v13 \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/erpnext-nginx:${VERSION} \
            -f build/erpnext-nginx/Dockerfile .
    - stage: "Build Frappe (all versions)"
      if: branch = master AND type != pull_request
      script:
        - |
          git clone https://github.com/frappe/frappe --branch version-12 && \
            cd frappe && \
            git fetch --tags && \
            export VERSION=$(git tag --list --sort=-version:refname "v12*" | sed -n 1p | sed -e 's#.*@\(\)#\1#') && \
            cd ..
        - |
          docker buildx build \
            --no-cache \
            --platform linux/amd64,linux/arm64 \
            --build-arg GIT_BRANCH=version-12 \
            --push \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-worker:v12 \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-worker:${VERSION} \
            -f build/frappe-worker/Dockerfile .
    - stage: "Build Frappe (all versions)"
      if: branch = master AND type != pull_request
      script:
        - |
          git clone https://github.com/frappe/frappe --branch version-12 && \
            cd frappe && \
            git fetch --tags && \
            export VERSION=$(git tag --list --sort=-version:refname "v12*" | sed -n 1p | sed -e 's#.*@\(\)#\1#') && \
            cd ..
        - |
          travis_wait 120 sleep infinity & docker buildx build \
            --no-cache \
            --platform linux/amd64,linux/arm64 \
            --build-arg GIT_BRANCH=version-12 \
            --push \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-nginx:v12 \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-nginx:${VERSION} \
            -f build/frappe-nginx/Dockerfile .
    - stage: "Build Frappe (all versions)"
      if: branch = master AND type != pull_request
      script:
        - |
          git clone https://github.com/frappe/frappe --branch version-12 && \
            cd frappe && \
            git fetch --tags && \
            export VERSION=$(git tag --list --sort=-version:refname "v12*" | sed -n 1p | sed -e 's#.*@\(\)#\1#') && \
            cd ..
        - |
          docker buildx build \
            --no-cache \
            --platform linux/amd64,linux/arm64 \
            --build-arg GIT_BRANCH=version-12 \
            --push \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-socketio:v12 \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-socketio:${VERSION} \
            -f build/frappe-socketio/Dockerfile .
    - stage: "Build ERPNext (all versions)"
      if: branch = master AND type != pull_request
      script:
        - |
          git clone https://github.com/frappe/erpnext --branch version-12 && \
            cd erpnext && \
            git fetch --tags && \
            export VERSION=$(git tag --list --sort=-version:refname "v12*" | sed -n 1p | sed -e 's#.*@\(\)#\1#') && \
            cd ..
        - |
          docker buildx build \
            --no-cache \
            --platform linux/amd64,linux/arm64 \
            --build-arg GIT_BRANCH=version-12 \
            --build-arg DOCKER_REGISTRY_PREFIX=${DOCKER_REGISTRY_PREFIX:=frappe} \
            --push \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/erpnext-worker:v12 \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/erpnext-worker:${VERSION} \
            -f build/erpnext-worker/Dockerfile .
    - stage: "Build ERPNext (all versions)"
      if: branch = master AND type != pull_request
      script:
        - |
          git clone https://github.com/frappe/erpnext --branch version-12 && \
            cd erpnext && \
            git fetch --tags && \
            export VERSION=$(git tag --list --sort=-version:refname "v12*" | sed -n 1p | sed -e 's#.*@\(\)#\1#') && \
            cd ..
        - |
          travis_wait 120 sleep infinity & docker buildx build \
            --no-cache \
            --platform linux/amd64,linux/arm64 \
            --build-arg GIT_BRANCH=version-12 \
            --build-arg DOCKER_REGISTRY_PREFIX=${DOCKER_REGISTRY_PREFIX:=frappe} \
            --push \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/erpnext-nginx:v12 \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/erpnext-nginx:${VERSION} \
            -f build/erpnext-nginx/Dockerfile .
    - stage: "Build Frappe (all versions)"
      if: branch = master AND type != pull_request
      script:
        - |
          git clone https://github.com/frappe/frappe --branch version-11 && \
            cd frappe && \
            git fetch --tags && \
            export VERSION=$(git tag --list --sort=-version:refname "v11*" | sed -n 1p | sed -e 's#.*@\(\)#\1#') && \
            cd ..
        - |
          docker buildx build \
            --no-cache \
            --platform linux/amd64,linux/arm64 \
            --build-arg GIT_BRANCH=version-11 \
            --push \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-worker:v11 \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-worker:${VERSION} \
            -f build/frappe-worker/Dockerfile .
    - stage: "Build Frappe (all versions)"
      if: branch = master AND type != pull_request
      script:
        - |
          git clone https://github.com/frappe/frappe --branch version-11 && \
            cd frappe && \
            git fetch --tags && \
            export VERSION=$(git tag --list --sort=-version:refname "v11*" | sed -n 1p | sed -e 's#.*@\(\)#\1#') && \
            cd ..
        - |
          travis_wait 120 sleep infinity & docker buildx build \
            --no-cache \
            --platform linux/amd64,linux/arm64 \
            --build-arg GIT_BRANCH=version-11 \
            --build-arg NODE_IMAGE_TAG=10-buster-slim \
            --push \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-nginx:v11 \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-nginx:${VERSION} \
            -f build/frappe-nginx/Dockerfile .
    - stage: "Build Frappe (all versions)"
      if: branch = master AND type != pull_request
      script:
        - |
          git clone https://github.com/frappe/frappe --branch version-11 && \
            cd frappe && \
            git fetch --tags && \
            export VERSION=$(git tag --list --sort=-version:refname "v11*" | sed -n 1p | sed -e 's#.*@\(\)#\1#') && \
            cd ..
        - |
          docker buildx build \
            --no-cache \
            --platform linux/amd64,linux/arm64 \
            --build-arg GIT_BRANCH=version-11 \
            --push \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-socketio:v11 \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/frappe-socketio:${VERSION} \
            -f build/frappe-socketio/Dockerfile .
    - stage: "Build ERPNext (all versions)"
      if: branch = master AND type != pull_request
      script:
        - |
          git clone https://github.com/frappe/erpnext --branch version-11 && \
            cd erpnext && \
            git fetch --tags && \
            export VERSION=$(git tag --list --sort=-version:refname "v11*" | sed -n 1p | sed -e 's#.*@\(\)#\1#') && \
            cd ..
        - |
          docker buildx build \
            --no-cache \
            --platform linux/amd64,linux/arm64 \
            --build-arg GIT_BRANCH=version-11 \
            --build-arg DOCKER_REGISTRY_PREFIX=${DOCKER_REGISTRY_PREFIX:=frappe} \
            --push \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/erpnext-worker:v11 \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/erpnext-worker:${VERSION} \
            -f build/erpnext-worker/Dockerfile .
    - stage: "Build ERPNext (all versions)"
      if: branch = master AND type != pull_request
      script:
        - |
          git clone https://github.com/frappe/erpnext --branch version-11 && \
            cd erpnext && \
            git fetch --tags && \
            export VERSION=$(git tag --list --sort=-version:refname "v11*" | sed -n 1p | sed -e 's#.*@\(\)#\1#') && \
            cd ..
        - |
          travis_wait 120 sleep infinity & docker buildx build \
            --no-cache \
            --platform linux/amd64,linux/arm64 \
            --build-arg GIT_BRANCH=version-11 \
            --build-arg NODE_IMAGE_TAG=10-buster-slim \
            --build-arg DOCKER_REGISTRY_PREFIX=${DOCKER_REGISTRY_PREFIX:=frappe} \
            --push \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/erpnext-nginx:v11 \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/erpnext-nginx:${VERSION} \
            -f build/erpnext-nginx/Dockerfile .
    - stage: "Build and test edge images"
      if: type = pull_request
      before_install:
        - sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        - sudo chmod +x /usr/local/bin/docker-compose
        - sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
        - sudo apt-get update && sudo apt-get -y install w3m
      script:
        - docker build -t frappe/frappe-socketio:edge -f build/frappe-socketio/Dockerfile .
        - docker build -t frappe/frappe-worker:develop -f build/frappe-worker/Dockerfile .
        - docker build -t frappe/erpnext-worker:edge -f build/erpnext-worker/Dockerfile .
        - docker build -t frappe/frappe-nginx:develop -f build/frappe-nginx/Dockerfile .
        - docker build -t frappe/erpnext-nginx:edge -f build/erpnext-nginx/Dockerfile .
        - ./tests/docker-test.sh
    - stage: "Pull and test edge images"
      if: branch = develop AND type != pull_request
      before_install:
        - sudo apt-get update && sudo apt-get -y install docker-compose w3m
      script:
        - ./tests/docker-test.sh
    - stage: "Helm Chart Release"
      if: branch = master AND type != pull_request
      env:
        - GIT_SSH_COMMAND="ssh -i ${TRAVIS_BUILD_DIR}/deploy_key"
      before_install:
        - openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv -in deploy_key.enc -out deploy_key -d;
          chmod 400 deploy_key;
        - ssh-keyscan github.com >> $HOME/.ssh/known_hosts 2>/dev/null;
      install:
        - pip install --upgrade pip
      script:
        - git clone git@github.com:frappe/helm.git && cd helm
        - pip install -r release_wizard/requirements.txt
        - ./release_wizard/wizard 12 patch --remote origin --ci
    - stage: "Build Frappe bench development environment (latest)"
      if: branch = develop AND type != pull_request
      script:
        - |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t ${DOCKER_REGISTRY_PREFIX:=frappe}/bench:latest \
            -f build/bench/Dockerfile .

```

**Comment by revant** [comment]
I pushed frappe images,

- https://hub.docker.com/r/castlecraft/frappe-nginx
- https://hub.docker.com/r/castlecraft/frappe-worker
- https://hub.docker.com/r/castlecraft/frappe-socketio

no ERPNext images yet

**Comment by artykbasar** [comment]
> I pushed frappe images,
> 
> * https://hub.docker.com/r/castlecraft/frappe-nginx
> * https://hub.docker.com/r/castlecraft/frappe-worker
> * https://hub.docker.com/r/castlecraft/frappe-socketio
> 
> no ERPNext images yet

Hello Revent,

First, I want to thank you for starting to build the image for arm64.

I have seen your new Dockerfiles which are compatible with arm64, where we can build our own images.
Now the problem that I have started to face in last 5 days, when I build an image from provided Dockerfile "frappe-nginx" I get this error:
```
Step 10/22 : RUN cd /home/frappe/frappe-bench/apps/frappe     && yarn     && yarn run production     && yarn install --production=true
 ---> Running in 5a6f580122b4
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > bootstrap@4.5.0" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.5.0" has unmet peer dependency "popper.js@^1.16.0".
[4/4] Building fresh packages...
error /home/frappe/frappe-bench/apps/frappe/node_modules/phantomjs-prebuilt: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /home/frappe/frappe-bench/apps/frappe/node_modules/phantomjs-prebuilt
Output:
PhantomJS not found on PATH
Unexpected platform or architecture: linux/arm64
It seems there is no binary available for your platform/architecture
Try to install PhantomJS globally
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c cd /home/frappe/frappe-bench/apps/frappe     && yarn     && yarn run production     && yarn install --production=true' returned a non-zero code: 1
```

I was not getting this error week ago, What do you think I should do to address this issue?

**Comment by ChillarAnand** [comment]
Looks like all images are not yet available for arm64?

https://github.com/frappe/frappe_docker/blob/main/docs/single-compose-setup.md This setup still doesn't work with arm64.

**Comment by MohammedNoureldin** [comment]
Hi, @ChillarAnand

Have you found any reasonable solution or alternative?
